# Elongation velocity gradient

Elongation velocity gradient, followed by relaxation. The first velocity gradient is along the x-axis, others are along random orientations. The Henky strain `H` is the duration of the velocity gradient event. 

In [1]:
import numpy as np
np.random.seed(2022)
from scipy.interpolate import interp1d
import pywt

from ipywidgets import interactive
import ipywidgets as widgets

%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [15, 8]

output_file = 'inputs/elongation/scenario_elongation'

# Number of independent scenarios
n_scenarios = 5

# Henky strain
H = 10

# Relax after strain
relax = False

## Sample velocity gradient data

In [2]:
if relax:
    times = [[0,H,2*H]]*n_scenarios
else:
    times = [[0,H]]*n_scenarios
gradUs = []

for i in range(n_scenarios):
    gradU = np.diag([1,-.5,-.5])
    if i>0:
        # Rotate
        x = 2*np.pi*np.random.random()
        y = 2*np.pi*np.random.random()
        z = 2*np.pi*np.random.random()
        Rx = np.array([[1., 0, 0],
                      [0, np.cos(x), -np.sin(x) ],
                      [0, np.sin(x), np.cos(x)]
                      ])
        Ry = np.array([[np.cos(y), 0, np.sin(y)],
                      [0, 1, 0],
                      [-np.sin(y), 0, np.cos(y)]
                      ])
        Rz = np.array([[np.cos(z),  -np.sin(z), 0],
                      [np.sin(z), np.cos(z), 0],
                      [0, 0, 1]
                      ])
        R = Rx @ Ry @ Rz
        gradU = R @ gradU @ R.T
    if relax:
        gradUs.append([gradU, np.zeros((3,3)), np.zeros((3,3))])
    else:
        gradUs.append([gradU, np.zeros((3,3))])
gradUs

[[array([[ 1. ,  0. ,  0. ],
         [ 0. , -0.5,  0. ],
         [ 0. ,  0. , -0.5]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[ 0.35906263, -0.74102686, -0.03852961],
         [-0.74102686,  0.13920928,  0.03323562],
         [-0.03852961,  0.03323562, -0.49827192]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[-0.26776314,  0.21277127, -0.49914899],
         [ 0.21277127, -0.30506276, -0.45731141],
         [-0.49914899, -0.45731141,  0.5728259 ]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[-0.1556659 ,  0.07205345, -0.62669249],
         [ 0.07205345, -0.48492249, -0.13113821],
         [-0.62669249, -0.13113821,  0.64058839]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[-0.42127626,  0.19282065,  0.27332833],
         [ 0.19282065, -0.02771802,  0.66947211],
         [ 0.27332833,  0.66947211,  0.44899428]]),
  array([[0., 0

In [3]:
for i, (time, gradU) in enumerate(zip(times, gradUs)):
    np.savez_compressed(f"{output_file}_{i}", t=time, gradU=gradU)