# Elongation velocity gradient

Elongation velocity gradient, followed by relaxation. The first velocity gradient is along the x-axis, others are along random orientations. The Henky strain `H` is the duration of the velocity gradient event. 

In [5]:
import numpy as np
from scipy.interpolate import interp1d
import pywt

from ipywidgets import interactive
import ipywidgets as widgets

%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [15, 8]

output_file = 'inputs/elongation/scenario_elongation'

# Number of independent scenarios
n_scenarios = 5

# Henky strain
H = 5

## Sample velocity gradient data

In [6]:
times = [[0,H,H+1]]*n_scenarios
gradUs = []

for i in range(n_scenarios):
    gradU = np.diag([1,-.5,-.5])
    if i>0:
        # Rotate
        x = 2*np.pi*np.random.random()
        y = 2*np.pi*np.random.random()
        z = 2*np.pi*np.random.random()
        Rx = np.array([[1., 0, 0],
                      [0, np.cos(x), -np.sin(x) ],
                      [0, np.sin(x), np.cos(x)]
                      ])
        Ry = np.array([[np.cos(y), 0, np.sin(y)],
                      [0, 1, 0],
                      [-np.sin(y), 0, np.cos(y)]
                      ])
        Rz = np.array([[np.cos(z),  -np.sin(z), 0],
                      [np.sin(z), np.cos(z), 0],
                      [0, 0, 1]
                      ])
        R = Rx @ Ry @ Rz
        gradU = R @ gradU @ R.T
    gradUs.append([gradU, np.zeros((3,3)), np.zeros((3,3))])
gradUs

[[array([[ 1. ,  0. ,  0. ],
         [ 0. , -0.5,  0. ],
         [ 0. ,  0. , -0.5]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[-0.43212568, -0.25557343, -0.1785687 ],
         [-0.25557343,  0.46233415,  0.67238116],
         [-0.1785687 ,  0.67238116, -0.03020847]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[ 0.56914325,  0.65539909,  0.17635085],
         [ 0.65539909, -0.09823161,  0.10810542],
         [ 0.17635085,  0.10810542, -0.47091164]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
  array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 [array([[ 0.29576025, -0.68774639, -0.29565335],
         [-0.68774639,  0.09439397,  0.25552234],
         [-0.29565335,  0.25552234, -0.39015422]]),
  array([[0., 0., 0.],
   

In [7]:
for i, (time, gradU) in enumerate(zip(times, gradUs)):
    np.savez_compressed(f"{output_file}_{i}", t=time, gradU=gradU)